language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -U -r requirements-test.txt

script:
  - make test
  - make pep8
  - make version-check

after_success:
  - coveralls
