language: python

matrix:
  fast_finish: true
  include:
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.5-dev"
    - python: "nightly"
  allow_failures:
    - os: osx

# `travis lint` is marking this section as a false positive!
# References:
#  - https://github.com/travis-ci/travis-ci/issues/3663
#  - https://github.com/travis-ci/travis-ci/issues/5396
addons:
  apt:
    packages:
    - python3-dev

branches:
  only:
    - master
    - release

before_install:
  - echo Travis OS Name ... ${TRAVIS_OS_NAME}
  - echo Travis Python .... ${TRAVIS_PYTHON_VERSION}
  - echo Python Version ... $(python --version)

install:
  - pip install --upgrade pip
  - pip install --upgrade --requirement requirements-travis.txt

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: >
      VCS7dHeluFzEE+1vuHi/H3CEvDrknqIpxDANxor8tyB2Iu2ZrLHH/s6n7hwnaU6uxiq7oOo1s/
      cSiXw0UfSlY9CkjxKdP8U/RhYF200ngEBpm3vvfFynEZ5otnJNznQs3Vga9AxZKezTT8btkbO0
      pUj4YoswTl2OEl+i1esOk3iWPXA9vZdPFmO1XchmnFC+IzyMeA3V7uxfNwh8d0cvlTsFKDB3M+
      Wx5GpsSaVJbH09oRzDXN3Lsoe9Q+PYQ2dkIP0JkeMMMBi8/D0Zqrjy9m1i/VhW45hA9+h2qKsO
      C2TPjp3Oi6coeCyNaZWPjA8Wf/I6PiGs5LM8PoT7u7+irtRqIRSI9/yerPOzultl/Di/kHDF0D
      r73Zn7tisBGEeAQuqsFYBiwaRJzWoWuzd1tXNARkeF6x9t3lRSf/UMGG3rJSyqWsxvzgzPHtEh
      DhcKo4ZBCeliBlwwJlNpCGhOII687HqI859VOAAfpXyuQsAaAD+gBgFr11SijIiMv6wCgyFyJ0
      MNYFr2jCs+ziqtPunKT85hI4S/hCNiE+SN5IcbjCjFawmxXMHE2tdrOQJHyQbmEIeIfrFJUYWc
      LbSf8avF1iidrrBtQlQ0LqwnvdwzlOfdjaXJoPNeeXa1DwHcGlHQ+g1JENbqXYnFgCSp4LHzXN
      qZdaWaEQbXHRjHqX0=
